version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: instantsearch.js
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: "@primer/css" #TODO: remove when manually upgrading
    versions:
    - ">= 16"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 99
